apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: manolo-k8s-agent-v1
  namespace: kagent
spec:
  declarative:    
    modelConfig: default-model-config
    deployment:
      env:
      - name: LOG_LEVEL
        value: DEBUG
    stream: true
    systemMessage: "''"
    tools:
    - mcpServer:
        apiGroup: kagent.dev
        kind: RemoteMCPServer
        name: kagent-tool-server
        toolNames:
        - k8s_patch_resource
        - k8s_create_resource
        - k8s_apply_manifest
        - k8s_get_resources
        - k8s_get_pod_logs
        - k8s_get_resource_yaml
        - k8s_delete_resource
      type: McpServer
  description: An Kubernetes Expert AI Agent specializing in cluster operations, troubleshooting,
    and maintenance.
  type: Declarative