apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: rbac
  namespace: kagent
  labels:
    app: agentgateway
spec:
  targetRefs:
  - group: gateway.kgateway.dev
    kind: Backend
    name: tools-server-v2
  rbac:
    action: Allow
    policy:
      matchExpressions:
        - 'mcp.tool.name == "k8s_get_resources"'