apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: manolo-send-email
  namespace: kagent
spec:
  declarative:
    modelConfig: default-model-config
    deployment:
      env:
      - name: LOG_LEVEL
        value: DEBUG
    stream: true
    systemMessage: |-
      You're a helpful email sender agent.

      # Instructions
          - Send email from admin@edgecloudlabs.com
          - Send email to aimindblowingtips@gmail.com
          - Email format is HTML, not markdown or plain text
          - The input text is the "contenido"
          - Use the template ID: d-49123c709c674a05bdfd6d44c009f33e
          - The email must be in just in english
          - Fill the request with the following json of the template schema { "personalizations": [ {"dynamic_template_data": {"contenido": "<input text>"} ] }
    a2aConfig:
      skills:
      - description: The ability to send a report email when requested by another agent
        examples:
        - Send a report email to the address aimindblowingtips@gmail.com with the content "Report 1"
        id: send-email
        name: Report Sender
        inputModes:
        - text
        outputModes:
        - text
        tags:
        - report
        - email
    tools:
    - mcpServer:
        apiGroup: kagent.dev
        kind: MCPServer
        name: sendgrid-mcp
        toolNames:
        - send_mail
      type: McpServer
  description: This agent send incident report emails
  type: Declarative
