apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-sqlite-vec
  namespace: kagent
  labels:
    app: mcp-sqlite-vec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-sqlite-vec
  template:
    metadata:
      labels:
        app: mcp-sqlite-vec
    spec:
      containers:
      - name: mcp-sqlite-vec
        image: antonioberben/mcp-server-doc2vec:amd
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: OPENAI_API_KEY
        - name: SQLITE_DB_DIR
          valueFrom:
            configMapKeyRef:
              name: mcp-config
              key: SQLITE_DB_DIR
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mcp-config
              key: PORT
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-sqlite-vec
  namespace: kagent
spec:
  selector:
    app: mcp-sqlite-vec
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
---
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: sqlite-vec
  namespace: kagent
spec:
  config:
    sse:
      timeout: 5s
      url: http://mcp-sqlite-vec.kagent:3001/sse
  description: ""
---
apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: query-documentation
  namespace: kagent
spec:
  description: Agent to operate kubernetes
  modelConfig: openai-model-config
  systemMessage: |-
    Use your tool to answer any question about the Model Context Protocol (MCP). Use mcp for the product and latest for the version.
  tools:
  - mcpServer:
      toolNames:
      - query-documentation
      toolServer: sqlite-vec
    type: McpServer
  