apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: mcp-toolserver
  namespace: kagent
spec:
  description: Fetches a website and returns its content
  config:
    sse:
      url: http://mcpk8s.kagent.svc.cluster.local:3001/sse