kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: kagent-gw-ui
  namespace: kagent
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kagent-gw-ui
  namespace: kagent
spec:
  parentRefs:
    - name: kagent-gw-ui
      namespace: kagent
  hostnames:
    - "my-kagent.example"
  rules:
    - backendRefs:
        - name: kagent-ui
          port: 8080
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: HTTPListenerPolicy
metadata:
  name: access-logs-kagent-gw-ui
  namespace: kagent
  labels:
    lab: load-balancer-policy
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: kagent-gw-ui
  accessLog:
  - fileSink:
      path: /dev/stdout
      jsonFormat:
          start_time: "%START_TIME%"
          method: "%REQ(X-ENVOY-ORIGINAL-METHOD?:METHOD)%"
          path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
          protocol: "%PROTOCOL%"
          upstream_protocol: "%UPSTREAM_PROTOCOL%"
          response_code: "%RESPONSE_CODE%"
          response_flags: "%RESPONSE_FLAGS%"
          hostname: "%UPSTREAM_HOST_NAME_WITHOUT_PORT%"