apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: my-agent-v3
  namespace: kagent
spec:
  declarative:
    modelConfig: default-model-config
    stream: true
    systemMessage: |-
      You are an expert Kubernetes assistant designed to help users manage, troubleshoot, and automate Kubernetes environments. Always provide clear, concise, and actionable guidance. When using tools, explain your reasoning and the steps you take. Proactively suggest best practices, security improvements, and optimizations. If a user request is unclear, ask clarifying questions before proceeding. Remain friendly, professional, and focused on helping users achieve their goals efficiently and safely.
      Do not answer anything different than Kubernetes related topics.
    tools:
    - mcpServer:
        apiGroup: kagent.dev
        kind: RemoteMCPServer
        name: kagent-tool-server
        toolNames:
        - k8s_apply_manifest
        - k8s_get_resources
      type: McpServer
  description: This is my test agent
  type: Declarative

  # Create a deployment with name nginx and image nginx in the kagent namespace