#!/usr/bin/env bash
# cleanup.sh — tear down the Agentic AI Kagent lab in reverse install order.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INVOKED_DIR="$(pwd)"
if [[ "$SCRIPT_DIR" != "$INVOKED_DIR" ]]; then
  echo "ERROR: this script must be run from its own directory."
  echo "       cd $SCRIPT_DIR && ./cleanup.sh"
  exit 1
fi
REPO_ROOT="$SCRIPT_DIR"

if [[ -f "${REPO_ROOT}/.env" ]]; then
  set -a; source "${REPO_ROOT}/.env"; set +a
fi

REQUIRED_VARS=(KUBE_CONTEXT)
for v in "${REQUIRED_VARS[@]}"; do
  [[ -n "${!v:-}" ]] || { echo "missing $v" >&2; exit 1; }
done

LOG=$'\033[0;36m[clean ]\033[0m'
OK=$'\033[0;32m[ ok  ]\033[0m'
WARN=$'\033[0;33m[warn ]\033[0m'

wait_ns_gone() {
  local ns="$1"
  local WAIT_TIMEOUT=300
  local deadline=$(( $(date +%s) + WAIT_TIMEOUT ))
  while kubectl --context="$KUBE_CONTEXT" get ns "$ns" >/dev/null 2>&1; do
    if (( $(date +%s) > deadline )); then
      printf '%s namespace %s did not finish deleting after %ss — check stuck finalizers:\n' "$WARN" "$ns" "$WAIT_TIMEOUT"
      printf '       kubectl --context=%s get ns %s -o yaml | grep -A5 finalizers\n' "$KUBE_CONTEXT" "$ns"
      return 0
    fi
    sleep 5
  done
}

printf '%s == phase 1/10 — AccessPolicies ==\n' "$LOG"
kubectl --context="$KUBE_CONTEXT" delete --ignore-not-found \
  -f "${REPO_ROOT}/manifests/access-policy.yaml"

printf '%s == phase 2/10 — strip agent waypoint label ==\n' "$LOG"
# Removing the label makes the controller tear down the agentgateway waypoint
# (Gateway "agent-k8s-agent-waypoint") and revert the service routing.
kubectl --context="$KUBE_CONTEXT" -n kagent label agent k8s-agent \
  kagent.solo.io/waypoint- 2>/dev/null || true

printf '%s == phase 3/10 — custom agents + OpenClaw harness ==\n' "$LOG"
# Delete the AgentHarness first so the controller tears down its OpenShell sandbox.
kubectl --context="$KUBE_CONTEXT" delete --ignore-not-found \
  -f "${REPO_ROOT}/manifests/openclaw-agent.yaml"
kubectl --context="$KUBE_CONTEXT" delete --ignore-not-found \
  -f "${REPO_ROOT}/manifests/team1-agent.yaml" \
  -f "${REPO_ROOT}/manifests/team2-not-allowed-agent.yaml"

printf '%s == phase 4/10 — A2A gateway ==\n' "$LOG"
kubectl --context="$KUBE_CONTEXT" delete --ignore-not-found \
  -f "${REPO_ROOT}/manifests/a2a-gateway.yaml"

printf '%s == phase 5/10 — agentregistry ==\n' "$LOG"
helm --kube-context="$KUBE_CONTEXT" uninstall agentregistry -n agentregistry || true
kubectl --context="$KUBE_CONTEXT" delete --ignore-not-found \
  -f "${REPO_ROOT}/manifests/postgres-pgvector.yaml"

printf '%s == phase 6/10 — kagent + management ==\n' "$LOG"
helm --kube-context="$KUBE_CONTEXT" uninstall kagent-mgmt -n kagent || true
helm --kube-context="$KUBE_CONTEXT" uninstall kagent -n kagent || true
helm --kube-context="$KUBE_CONTEXT" uninstall kagent-crds -n kagent || true

printf '%s == phase 7/10 — OpenClaw harness backend (OpenShell + agent-sandbox) ==\n' "$LOG"
helm --kube-context="$KUBE_CONTEXT" uninstall openshell -n openshell || true
kubectl --context="$KUBE_CONTEXT" delete --ignore-not-found -f \
  "https://github.com/kubernetes-sigs/agent-sandbox/releases/download/${AGENT_SANDBOX_VERSION:-v0.4.6}/manifest.yaml" || true

printf '%s == phase 8/10 — agentgateway enterprise ==\n' "$LOG"
helm --kube-context="$KUBE_CONTEXT" uninstall enterprise-agentgateway -n agentgateway-system || true
helm --kube-context="$KUBE_CONTEXT" uninstall enterprise-agentgateway-crds -n agentgateway-system || true

printf '%s == phase 9/10 — istio ambient stack ==\n' "$LOG"
helm --kube-context="$KUBE_CONTEXT" uninstall ztunnel -n istio-system || true
helm --kube-context="$KUBE_CONTEXT" uninstall istio-cni -n istio-system || true
helm --kube-context="$KUBE_CONTEXT" uninstall istiod-solo -n istio-system || true
helm --kube-context="$KUBE_CONTEXT" uninstall istio-base -n istio-system || true

printf '%s == phase 10/10 — namespaces ==\n' "$LOG"
kubectl --context="$KUBE_CONTEXT" delete namespace --ignore-not-found \
  kagent agentgateway-system agentregistry istio-system openshell agent-sandbox-system
for ns in kagent agentgateway-system agentregistry istio-system openshell agent-sandbox-system; do
  wait_ns_gone "$ns"
done

# Cluster-scoped Gateway API CRDs are shared with anything else on the cluster
# that uses Gateway API. Only remove under an explicit flag.
if [[ "${TEARDOWN_GATEWAY_API_CRDS:-0}" == "1" ]]; then
  printf '%s removing Gateway API CRDs (TEARDOWN_GATEWAY_API_CRDS=1)\n' "$LOG"
  kubectl --context="$KUBE_CONTEXT" delete --ignore-not-found -f \
    "https://github.com/kubernetes-sigs/gateway-api/releases/download/${GATEWAY_API_VERSION:-v1.2.1}/standard-install.yaml"
else
  printf '%s skipping Gateway API CRDs (set TEARDOWN_GATEWAY_API_CRDS=1 to also remove)\n' "$WARN"
fi

rm -f "${REPO_ROOT}/manifests/istio-values-AUTOGENERATED.yaml"

printf '%s cleanup complete.\n' "$OK"
