#!/usr/bin/env bash
# deploy.sh — install the Agentic AI Kagent kagent-enterprise lab end-to-end.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INVOKED_DIR="$(pwd)"
if [[ "$SCRIPT_DIR" != "$INVOKED_DIR" ]]; then
  echo "ERROR: this script must be run from its own directory."
  echo "       cd $SCRIPT_DIR && ./deploy.sh"
  exit 1
fi
REPO_ROOT="$SCRIPT_DIR"

if [[ -f "${REPO_ROOT}/.env" ]]; then
  set -a; source "${REPO_ROOT}/.env"; set +a
fi

REQUIRED_VARS=(
  KUBE_CONTEXT
  OPENAI_API_KEY
  SOLO_ISTIO_LICENSE_KEY
  GLOO_GATEWAY_LICENSE_KEY
  AGENTGATEWAY_LICENSE_KEY
  ISTIO_VERSION
  ISTIO_IMAGE_TAG
  ISTIO_REPO
  ISTIO_HELM_REPO
  AGENTGATEWAY_VERSION
  KAGENT_ENT_VERSION
  AGENTREGISTRY_VERSION
  GATEWAY_API_VERSION
)
for v in "${REQUIRED_VARS[@]}"; do
  [[ -n "${!v:-}" ]] || { echo "missing $v" >&2; exit 1; }
done

LOG=$'\033[0;36m[deploy]\033[0m'
OK=$'\033[0;32m[ ok  ]\033[0m'
WARN=$'\033[0;33m[warn ]\033[0m'
FAIL=$'\033[0;31m[fail ]\033[0m'

apply_ns() {
  local ns="$1"
  kubectl --context="$KUBE_CONTEXT" create namespace "$ns" \
    --dry-run=client -o yaml | kubectl --context="$KUBE_CONTEXT" apply -f -
}

wait_for_lb_hostname() {
  local ns="$1" svc="$2" out=""
  for i in {1..60}; do
    out=$(kubectl --context="$KUBE_CONTEXT" -n "$ns" get svc "$svc" \
      -o jsonpath="{.status.loadBalancer.ingress[0]['hostname','ip']}" 2>/dev/null || echo "")
    [[ -n "$out" ]] && { echo "$out"; return 0; }
    sleep 5
  done
  return 1
}

printf '%s == phase 1/14 — namespaces ==\n' "$LOG"
apply_ns istio-system
apply_ns kagent
apply_ns agentgateway-system
printf '%s namespaces ready\n' "$OK"

printf '%s == phase 2/14 — kagent secrets (llm-api-keys + OIDC + OBO signing key) ==\n' "$LOG"
kubectl --context="$KUBE_CONTEXT" -n kagent create secret generic llm-api-keys \
  --from-literal=OPENAI_API_KEY="$OPENAI_API_KEY" \
  --dry-run=client -o yaml | kubectl --context="$KUBE_CONTEXT" apply -f -
# kagent-enterprise-oidc-secret value must match the staticClients[].secret
# field in manifests/management-values.yaml — the controller crashes on
# startup if this Secret is missing.
kubectl --context="$KUBE_CONTEXT" -n kagent create secret generic kagent-enterprise-oidc-secret \
  --from-literal=clientSecret=kagent-enterprise-secret \
  --dry-run=client -o yaml | kubectl --context="$KUBE_CONTEXT" apply -f -
# OBO signing key: the controller signs OBO JWTs with a 2048-bit RSA key
# read from secret "jwt" key "jwt". Without it the controller logs "obo
# token handler not ready" and every A2A call from the UI fails with 500.
# Cache the key in .certs/ so re-runs and rotations stay stable.
mkdir -p "${REPO_ROOT}/.certs"
OBO_KEY="${REPO_ROOT}/.certs/obo-signing-key.pem"
if [[ ! -s "$OBO_KEY" ]]; then
  openssl genpkey -algorithm RSA -out "$OBO_KEY" -pkeyopt rsa_keygen_bits:2048 2>/dev/null
fi
kubectl --context="$KUBE_CONTEXT" -n kagent create secret generic jwt \
  --from-file=jwt="$OBO_KEY" \
  --dry-run=client -o yaml | kubectl --context="$KUBE_CONTEXT" apply -f -
printf '%s llm-api-keys + kagent-enterprise-oidc-secret + jwt applied\n' "$OK"

printf '%s == phase 3/14 — Gateway API CRDs (%s) ==\n' "$LOG" "$GATEWAY_API_VERSION"
kubectl --context="$KUBE_CONTEXT" apply -f \
  "https://github.com/kubernetes-sigs/gateway-api/releases/download/${GATEWAY_API_VERSION}/standard-install.yaml"
printf '%s Gateway API CRDs applied\n' "$OK"

printf '%s == phase 4/14 — render istio values ==\n' "$LOG"
cat > "${REPO_ROOT}/manifests/istio-values-AUTOGENERATED.yaml" <<EOF
global:
  hub: ${ISTIO_REPO}
  tag: ${ISTIO_IMAGE_TAG}
profile: ambient
EOF
printf '%s wrote manifests/istio-values-AUTOGENERATED.yaml\n' "$OK"

printf '%s == phase 5/14 — istio-base CRDs ==\n' "$LOG"
helm --kube-context="$KUBE_CONTEXT" upgrade --install istio-base \
  "oci://${ISTIO_HELM_REPO}/base" \
  --namespace istio-system \
  --version "$ISTIO_VERSION"
kubectl --context="$KUBE_CONTEXT" wait --for=condition=Established \
  crd/authorizationpolicies.security.istio.io --timeout=60s
printf '%s istio-base installed, AuthorizationPolicy CRD established\n' "$OK"

printf '%s == phase 6/14 — istiod control plane ==\n' "$LOG"
helm --kube-context="$KUBE_CONTEXT" upgrade --install istiod-solo \
  "oci://${ISTIO_HELM_REPO}/istiod" \
  --version "$ISTIO_VERSION" \
  --namespace istio-system \
  --values "${REPO_ROOT}/manifests/istio-values-AUTOGENERATED.yaml"
printf '%s istiod-solo installed\n' "$OK"

printf '%s == phase 7/14 — istio-cni ==\n' "$LOG"
helm --kube-context="$KUBE_CONTEXT" upgrade --install istio-cni \
  "oci://${ISTIO_HELM_REPO}/cni" \
  --version "$ISTIO_VERSION" \
  --namespace istio-system \
  --values "${REPO_ROOT}/manifests/istio-values-AUTOGENERATED.yaml"
printf '%s istio-cni installed\n' "$OK"

printf '%s == phase 8/14 — ztunnel ==\n' "$LOG"
helm --kube-context="$KUBE_CONTEXT" upgrade --install ztunnel \
  "oci://${ISTIO_HELM_REPO}/ztunnel" \
  --version "$ISTIO_VERSION" \
  --namespace istio-system \
  --values "${REPO_ROOT}/manifests/istio-values-AUTOGENERATED.yaml"
printf '%s ztunnel installed\n' "$OK"

printf '%s == phase 9/14 — wait for mesh, enrol kagent ns in ambient ==\n' "$LOG"
kubectl --context="$KUBE_CONTEXT" -n istio-system wait \
  --for=condition=ready pod -l app=istiod --timeout=120s
kubectl --context="$KUBE_CONTEXT" -n istio-system wait \
  --for=condition=ready pod -l app=ztunnel --timeout=120s
kubectl --context="$KUBE_CONTEXT" label namespace kagent \
  istio.io/dataplane-mode=ambient --overwrite
printf '%s kagent namespace enrolled in ambient mesh\n' "$OK"

printf '%s == phase 10/14 — agentgateway enterprise (%s) ==\n' "$LOG" "$AGENTGATEWAY_VERSION"
helm --kube-context="$KUBE_CONTEXT" upgrade --install \
  --namespace agentgateway-system \
  --version "$AGENTGATEWAY_VERSION" \
  enterprise-agentgateway-crds \
  oci://us-docker.pkg.dev/solo-public/enterprise-agentgateway/charts/enterprise-agentgateway-crds
helm --kube-context="$KUBE_CONTEXT" upgrade --install \
  --namespace agentgateway-system \
  --version "$AGENTGATEWAY_VERSION" \
  enterprise-agentgateway \
  oci://us-docker.pkg.dev/solo-public/enterprise-agentgateway/charts/enterprise-agentgateway \
  --set-string licensing.licenseKey="${AGENTGATEWAY_LICENSE_KEY}"
printf '%s enterprise-agentgateway installed\n' "$OK"

printf '%s == phase 11/14 — kagent enterprise (%s) ==\n' "$LOG" "$KAGENT_ENT_VERSION"
helm --kube-context="$KUBE_CONTEXT" upgrade --install kagent-crds \
  oci://us-docker.pkg.dev/solo-public/kagent-enterprise-helm/charts/kagent-enterprise-crds \
  --namespace kagent \
  --version "$KAGENT_ENT_VERSION"
kubectl --context="$KUBE_CONTEXT" wait --for=condition=Established \
  crd/agents.kagent.dev --timeout=60s
helm --kube-context="$KUBE_CONTEXT" upgrade --install kagent \
  oci://us-docker.pkg.dev/solo-public/kagent-enterprise-helm/charts/kagent-enterprise \
  --namespace kagent \
  --version "$KAGENT_ENT_VERSION" \
  --values "${REPO_ROOT}/manifests/kagent-enterprise-values.yaml" \
  --set licensing.licenseKey="${GLOO_GATEWAY_LICENSE_KEY}"
printf '%s kagent-enterprise installed\n' "$OK"

printf '%s == phase 12/14 — management UI ==\n' "$LOG"
helm --kube-context="$KUBE_CONTEXT" upgrade --install kagent-mgmt \
  oci://us-docker.pkg.dev/solo-public/solo-enterprise-helm/charts/management \
  --namespace kagent \
  --version "$KAGENT_ENT_VERSION" \
  --values "${REPO_ROOT}/manifests/management-values.yaml" \
  --set licensing.licenseKey="${GLOO_GATEWAY_LICENSE_KEY}"
printf '%s management UI installed\n' "$OK"

printf '%s == phase 13/14 — agentregistry + postgres ==\n' "$LOG"
mkdir -p "${REPO_ROOT}/.certs"
JWT_FILE="${REPO_ROOT}/.certs/agent-registry-jwt"
if [[ ! -s "$JWT_FILE" ]]; then
  openssl rand -hex 32 > "$JWT_FILE"
  printf '%s generated new agent-registry JWT (cached in .certs/)\n' "$OK"
else
  printf '%s reusing cached agent-registry JWT\n' "$OK"
fi
AGENT_REGISTRY_JWT="$(cat "$JWT_FILE")"

kubectl --context="$KUBE_CONTEXT" apply -f "${REPO_ROOT}/manifests/postgres-pgvector.yaml"

helm --kube-context="$KUBE_CONTEXT" upgrade --install agentregistry \
  oci://ghcr.io/agentregistry-dev/agentregistry/charts/agentregistry \
  --namespace agentregistry \
  --create-namespace \
  --version "$AGENTREGISTRY_VERSION" \
  --set config.jwtPrivateKey="$AGENT_REGISTRY_JWT" \
  --set database.postgres.bundled.enabled=false \
  --set-string database.postgres.url="postgres://agentregistry:agentregistry@postgres-pgvector.agentregistry.svc.cluster.local:5432/agent-registry?sslmode=disable" \
  --set database.postgres.vectorEnabled=true \
  --set service.type=LoadBalancer \
  -f "${REPO_ROOT}/manifests/agentregistry-values.yaml" \
  --set config.disableBuiltinSeed="false"
printf '%s agentregistry installed\n' "$OK"

printf '%s == phase 14/14 — A2A gateway, agents, AccessPolicy ==\n' "$LOG"
# Wait for the kagent CRDs (Agent) and gateway-api Gateway CRD to be Established
# before applying any CRs that depend on them.
kubectl --context="$KUBE_CONTEXT" wait --for=condition=Established \
  crd/gateways.gateway.networking.k8s.io --timeout=60s
kubectl --context="$KUBE_CONTEXT" wait --for=condition=Established \
  crd/agents.kagent.dev --timeout=60s

# A2A data path: the controller proxies agent-to-agent calls through this
# enterprise-agentgateway (see a2aBaseUrl in kagent-enterprise-values.yaml).
kubectl --context="$KUBE_CONTEXT" apply -f "${REPO_ROOT}/manifests/a2a-gateway.yaml"

kubectl --context="$KUBE_CONTEXT" apply -f "${REPO_ROOT}/manifests/team1-agent.yaml"
kubectl --context="$KUBE_CONTEXT" apply -f "${REPO_ROOT}/manifests/team2-not-allowed-agent.yaml"

# AccessPolicy enforcement requires the target Agent to be fronted by an
# agentgateway waypoint. Labeling the Agent makes the kagent controller
# provision the waypoint (Gateway "agent-k8s-agent-waypoint") and its HTTPRoute,
# and repoint the k8s-agent service's istio.io/use-waypoint label automatically.
# The community agents are created by the kagent-enterprise chart (phase 11);
# wait for the target Agent to exist before labeling it.
for i in {1..30}; do
  kubectl --context="$KUBE_CONTEXT" -n kagent get agent k8s-agent >/dev/null 2>&1 && break
  sleep 2
done
kubectl --context="$KUBE_CONTEXT" -n kagent label agent k8s-agent \
  kagent.solo.io/waypoint=true --overwrite

# The controller reconciles the label into the waypoint Gateway. It can be
# briefly unavailable on first boot (it depends on the solo-enterprise-ui OIDC
# endpoint), so wait for it to be Ready before expecting the waypoint.
kubectl --context="$KUBE_CONTEXT" -n kagent rollout status \
  deploy/kagent-controller --timeout=300s
# The Gateway is created asynchronously; poll until it exists before waiting on
# its Programmed condition (kubectl wait errors immediately on a missing object).
for i in {1..60}; do
  kubectl --context="$KUBE_CONTEXT" -n kagent get gateway agent-k8s-agent-waypoint \
    >/dev/null 2>&1 && break
  sleep 5
done
kubectl --context="$KUBE_CONTEXT" -n kagent wait \
  --for=condition=Programmed gateway/agent-k8s-agent-waypoint --timeout=120s

# AccessPolicy is the native kagent-enterprise authorization resource. The
# controller translates each one into an EnterpriseAgentgatewayPolicy enforced
# by the target agent's waypoint. This replaces the hand-written
# EnterpriseAgentgatewayPolicy and Istio AuthorizationPolicy manifests.
kubectl --context="$KUBE_CONTEXT" apply -f "${REPO_ROOT}/manifests/access-policy.yaml"
printf '%s A2A gateway, agents, and AccessPolicies applied\n' "$OK"

printf '%s == discovering endpoints ==\n' "$LOG"
# On kind + MetalLB on macOS the LB IPs live on the docker bridge and aren't
# routable from the host — prefer port-forward and surface the LB IP as a hint.
KAGENT_URL=$(wait_for_lb_hostname kagent solo-enterprise-ui || true)
REG_URL=$(wait_for_lb_hostname agentregistry agentregistry || true)
cat <<EOF
${OK} Solo Enterprise UI
    port-forward:  kubectl --context=${KUBE_CONTEXT} -n kagent port-forward svc/solo-enterprise-ui 8080:80
    then open:     http://localhost:8080
    LB IP (Linux): ${KAGENT_URL:-pending}
${OK} AgentRegistry
    port-forward:  kubectl --context=${KUBE_CONTEXT} -n agentregistry port-forward svc/agentregistry 12121:12121
    then open:     http://localhost:12121
    LB IP (Linux): ${REG_URL:-pending}:12121
EOF

printf '%s deploy complete. Run ./test.sh to verify policy enforcement.\n' "$OK"
