adminUser: admin
adminPassword: finops

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki.telemetry.svc.cluster.local:3100
        access: proxy
        isDefault: false
      - name: Tempo
        type: tempo
        url: http://tempo.telemetry.svc.cluster.local:3100
        access: proxy
        isDefault: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            enabled: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: FinOps
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

persistence:
  enabled: false
