providers:
  default: anthropic
  anthropic:
    apiKey: ${ANTHROPIC_API_KEY}

otel:
  tracing:
    enabled: true
    exporter:
      otlp:
        endpoint: http://opentelemetry-collector-audit.telemetry.svc.cluster.local:4317
        timeout: 15
        insecure: true
  logging:
    enabled: true
    exporter:
      otlp:
        endpoint: http://opentelemetry-collector-audit.telemetry.svc.cluster.local:4317
        timeout: 15
        insecure: true
